In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/Users/tinashem/Downloads/DOR_Parcel.csv')
data

/var/folders/zy/1n1cqtl540n_747vnk5pgbrm0000gn/T/ipykernel_5516/1883866521.py:1: DtypeWarning: Columns (4,22,26,28,29,30,31,32,33,34,35,36,37) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/Users/tinashem/Downloads/DOR_Parcel.csv')

,OBJECTID,RECSUB,BASEREG,MAPREG,PARCEL,RECMAP,STCOD,HOUSE,SUF,UNIT,...,STEX_FRAC,STEX_SUF,SEPARATED_RIGHTS,MUNIMENT_TYPE,MUNIMENT_ID,DOR_REVIEW,OPA_REVIEW,PWD_REVIEW,Shape__Area,Shape__Length
0,1,,055N020105,055N020105,0105,055N02,61140.0,4029.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.472656,58.177404
1,2,,057N030286,057N030286,0286,057N03,61140.0,4218.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,235.445312,91.918808
2,3,,123N200109,123N200109,0109,123N20,61300.0,6055.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,253.750000,69.684862
3,4,,005N090046,005N090046,0046,005N09,61320.0,408.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,191.496094,63.778822
4,5,,133N080026,133N080026,0026,133N08,61360.0,616.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,306.703125,98.582369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607309,607310,,008S210145,008S210145,145,008S21,61000.0,2213.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146.828125,61.270649
607310,607311,,008S220275,008S220275,275,008S22,61000.0,2423.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163.671875,67.149234
607311,607312,,008S230432,008S230432,432,008S23,61000.0,2639.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.992188,62.794045
607312,607313,,008S230104,008S230104,104,008S23,61000.0,2723.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.652344,49.849531
607313,607314,,090N220035,090N220035,35,090N22,61040.0,4723.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,474.316406,117.987472

In [3]:
data.dtypes

OBJECTID              int64
RECSUB               object
BASEREG              object
MAPREG               object
PARCEL               object
RECMAP               object
STCOD               float64
HOUSE               float64
SUF                  object
UNIT                 object
STEX                float64
STDIR                object
STNAM                object
STDESSUF             object
ELEV_FLAG             int64
TOPELEV             float64
BOTELEV             float64
CONDOFLAG             int64
MATCHFLAG           float64
INACTDATE            object
ORIG_DATE            object
STATUS              float64
GEOID                object
STDES                object
ADDR_SOURCE          object
ADDR_STD             object
COMMENTS             object
PIN                 float64
FRAC                 object
UNIT_TYPE            object
STEX_FRAC            object
STEX_SUF             object
SEPARATED_RIGHTS     object
MUNIMENT_TYPE        object
MUNIMENT_ID          object
DOR_REVIEW           object
OPA_REVIEW           object
PWD_REVIEW           object
Shape__Area         float64
Shape__Length       float64
dtype: object

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607314 entries, 0 to 607313
Data columns (total 40 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   OBJECTID          607314 non-null  int64
 1   RECSUB            584621 non-null  object
 2   BASEREG           607137 non-null  object
 3   MAPREG            607156 non-null  object
 4   PARCEL            606972 non-null  object
 5   RECMAP            607142 non-null  object
 6   STCOD             605691 non-null  float64
 7   HOUSE             594336 non-null  float64
 8   SUF               3143 non-null    object
 9   UNIT              8448 non-null    object
 10  STEX              13102 non-null   float64
 11  STDIR             239260 non-null  object
 12  STNAM             601593 non-null  object
 13  STDESSUF          48785 non-null   object
 14  ELEV_FLAG         607314 non-null  int64
 15  TOPELEV           607314 non-null  float64
 16  BOTELEV           607314 non-null  float64
 17  CONDOFLAG         607314 non-null  int64
 18  MATCHFLAG         577680 non-null  float64
 19  INACTDATE         589925 non-null  object
 20  ORIG_DATE         595110 non-null  object
 21  STATUS            607305 non-null  float64
 22  GEOID             61 non-null      object
 23  STDES             601066 non-null  object
 24  ADDR_SOURCE       607030 non-null  object
 25  ADDR_STD          594208 non-null  object
 26  COMMENTS          18028 non-null   object
 27  PIN               578284 non-null  float64
 28  FRAC              453 non-null     object
 29  UNIT_TYPE         6 non-null       object
 30  STEX_FRAC         9 non-null       object
 31  STEX_SUF          6 non-null       object
 32  SEPARATED_RIGHTS  419 non-null     object
 33  MUNIMENT_TYPE     27653 non-null   object
 34  MUNIMENT_ID       27586 non-null   object
 35  DOR_REVIEW        33881 non-null   object
 36  OPA_REVIEW        33471 non-null   object
 37  PWD_REVIEW        33498 non-null   object
 38  Shape__Area       607283 non-null  float64
 39  Shape__Length     607283 non-null  float64
dtypes: float64(10), int64(3), object(27)
memory usage: 185.3+ MB